conf.app:
  php_settings:
    display_errors: true
    display_startup_errors: true
    error_log: ../../data/logs/php.log

  silex:
    debug: true
    modules:
      0:
        name: roadmap
        url: raggam.net

  monolog:
    app: app.log
    handlers:
      sql: sql.log
      controller: controller.log

  template:
    engine: twig

  database:
    adapter: Mysql
    driver: pdo_mysql
    host: raggamneut33.mysql.db
    dbname: raggamneut33
    user: raggamneut33
    password: G83tRsBnPFYC
    charset: utf8
